---

- hosts: all
  become: true
  tasks:

  - name: Update Reposotory Index
    apt:
      update_cache: yes

  - name: Install Apache2 Package on Ubuntu Servers
    apt:
      name: apache2
      state: latest

  - name: Install PHP Support for Apache
    apt:
      name: libapache2-mod-php
      state: latest 
