---

- hosts: all
  become: true
  tasks:

  - name: Install Apache and PHP Packages
    package:
      name:
        - "{{ apache_pkg }}"
        - "{{ php_pkg }}"
      state: latest
      update_cache: yes
