---

- hosts: all
  become: true
  tasks:

  - name: Install Apache2 on Ubuntu Servers
    apt:
      name: apache2
      state: latest
      update_cache: yes
      force_apt_get: yes
      autoclean: yes
      autoremove: yes

  - name: Install Support PHP Module for Apache
    apt:
      name: libapache2-mod-php
      state: latest
      update_cache: yes
      force_apt_get: yes
      autoclean: yes
      autoremove: yes
