---

- hosts: all
  become: true
  tasks:


  - name: Remove Apache2 Package on Ubuntu Servers
    apt:
      name: apache2
      state: absent

  - name: Remove PHP Support for Apache
    apt:
      name: libapache2-mod-php
      state: absent 
