---

- hosts: all
  become: true
  tasks:

  - name: Remove Apache and PHP Packages from all Systems
    package:
      name:
        - "{{ apache_pkg }}"
        - "{{ php_pkg }}"
      state: absent
