---

- hosts: all
  become: true
  tasks:

  - name: Update and Upgrade, Debian, Ubuntu Systems
    apt:
      upgrade: yes
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Update Red Hat Clone Systems
    dnf:
      update_cache: yes
      name: "*"
      state: latest
    when: ansible_distribution in ["Red Hat", "CentOS", "Oracle", "AlmaLinux", "RockyLinux"]
